# Generated by Django 4.2.5 on 2023-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold_price',
            field=models.FloatField(default=0, verbose_name='Umumiy sotilgan narxi'),
        ),
    ]
