# Generated by Django 4.2.5 on 2023-11-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0002_product_total_sold_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Tovar ', 'verbose_name_plural': 'Tovarlar'},
        ),
        migrations.AlterModelOptions(
            name='salesevent',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
