# Generated by Django 4.2.5 on 2023-11-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0004_alter_productproduction_options'),
        ('Azamat_seh', '0004_product_level_product_lft_product_parent_and_more'),
    ]

    operations = [
    ]
