# Generated by Django 4.2.5 on 2023-11-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0005_merge_20231118_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduction',
            name='product',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='Azamat_seh.product', verbose_name='Produkt'),
        ),
    ]
