# Generated by Django 4.2.5 on 2023-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0006_alter_productproduction_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='buyer',
            field=models.CharField(max_length=250, verbose_name='Sotuvchi'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='seller',
            field=models.CharField(max_length=250, verbose_name='Haridor'),
        ),
    ]
