# Generated by Django 4.2.5 on 2023-12-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0007_alter_sales_buyer_alter_sales_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproduction',
            options={'ordering': ['-date'], 'verbose_name': 'Tovar ', 'verbose_name_plural': 'Tovarlar Ishlab Chiqarish'},
        ),
        migrations.RenameField(
            model_name='productproduction',
            old_name='production_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='arrival_time',
            new_name='date',
        ),
    ]
