# Generated by Django 4.2.5 on 2024-01-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0008_alter_productproduction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_sold_price',
        ),
    ]
