# Generated by Django 4.2.5 on 2024-01-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0009_remove_product_total_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesevent',
            name='profit',
            field=models.FloatField(default=0, verbose_name='Foyda'),
        ),
    ]
