# Generated by Django 4.2.5 on 2024-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0011_alter_productproduction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.5, verbose_name='Vazni'),
            preserve_default=False,
        ),
    ]
