# Generated by Django 4.2.5 on 2024-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Azamat_seh', '0012_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(verbose_name='Vazni (kg)'),
        ),
    ]
