# Generated by Django 4.2.5 on 2023-11-08 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('sell_price', models.FloatField(verbose_name='Sotuv narxi')),
                ('currency', models.CharField(choices=[('sum', "So'm"), ('$', 'USD')], default='$', max_length=3, verbose_name='Valyuta birligi')),
                ('measurement', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('m', 'Metr'), ('ta', 'Dona')], max_length=2, verbose_name="O'lchov birligi")),
                ('total', models.FloatField(default=0, verbose_name='Umumiy')),
                ('notification_limit', models.IntegerField(default=500, verbose_name='Ogohlantirish')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Anvaraka_sklad.product', verbose_name="Bo'limlar")),
            ],
            options={
                'verbose_name': 'Mahsulot ',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Dona')),
                ('quantity_in_measurement', models.FloatField(verbose_name='Miqdor')),
                ('box', models.IntegerField(default=0, verbose_name='Qutilar soni')),
                ('price', models.FloatField(default=0, verbose_name='Narxi')),
                ('total_price', models.FloatField(default=0, verbose_name='Umumiy narxi')),
                ('arrival_time', models.DateTimeField(auto_now_add=True, verbose_name='Keltirilgan sana')),
                ('component', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='Anvaraka_sklad.product', verbose_name='Keltirilgan mahsulot ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehoueeeper', to=settings.AUTH_USER_MODEL, verbose_name='xodim')),
            ],
            options={
                'verbose_name': 'Keltirilgan Mahsulot ',
                'verbose_name_plural': 'Ombor',
            },
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100, verbose_name='Xaridor')),
                ('sold_time', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan sana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salsekeeper', to=settings.AUTH_USER_MODEL, verbose_name='xodim')),
            ],
            options={
                'verbose_name': 'Sotilgan Mahsulot ',
                'verbose_name_plural': 'Sotuvlar',
            },
        ),
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name="To'lov")),
                ('paid', models.DateTimeField(auto_now_add=True, verbose_name="T'olov qilingan sana")),
                ('selling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Anvaraka_sklad.selling')),
            ],
            options={
                'verbose_name': "To'lov ",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Dona')),
                ('quantity_in_measurement', models.FloatField(verbose_name='Miqdor')),
                ('box', models.IntegerField(default=0, verbose_name='Qutilar soni')),
                ('price', models.FloatField(default=0, verbose_name='Narxi')),
                ('total_price', models.FloatField(default=0, verbose_name='Umumiy narxi')),
                ('component', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='Anvaraka_sklad.product', verbose_name='Sotilgan mahsulot ')),
                ('selling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anvaraka_sklad.selling')),
            ],
            options={
                'verbose_name': 'Sotilgan tovar ',
                'verbose_name_plural': 'Sotuv',
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Dona')),
                ('quantity_in_measurement', models.FloatField(unique=True, verbose_name='Miqdor')),
                ('box', models.IntegerField(default=0, verbose_name='Qutilar soni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='Anvaraka_sklad.product', verbose_name='product')),
            ],
            options={
                'ordering': ('-quantity',),
            },
        ),
    ]
