# Generated by Django 4.2.6 on 2023-11-01 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price', models.FloatField(verbose_name='Narx')),
                ('measurement', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('pc', 'Dona')], max_length=2, verbose_name="O'lchov birligi")),
                ('total', models.FloatField(default=0, verbose_name='Umumiy')),
                ('notification_limit', models.IntegerField(default=500, verbose_name='Ogohlantirish')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Anvaraka_sklad.product', verbose_name="Bo'limlar")),
            ],
            options={
                'verbose_name': 'Mahsulot ',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
