# Generated by Django 4.2.5 on 2023-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesevent',
            name='currency',
            field=models.CharField(choices=[('sum', "So'm"), ('$', 'USD')], default='$', max_length=3, verbose_name='Valyuta birligi'),
        ),
    ]
