# Generated by Django 4.2.5 on 2023-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0002_salesevent_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity_in_measurement',
            field=models.FloatField(verbose_name='Miqdor'),
        ),
        migrations.AlterUniqueTogether(
            name='productcomponent',
            unique_together={('product', 'quantity_in_measurement')},
        ),
    ]
