# Generated by Django 4.2.5 on 2024-01-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0004_remove_productcomponent_box_remove_sales_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='profit',
            field=models.FloatField(default=0, verbose_name='Foyda'),
        ),
    ]
