# Generated by Django 4.2.5 on 2023-11-03 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anvaraka_sklad', '0004_alter_product_measurement_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salsekeeper', to=settings.AUTH_USER_MODEL, verbose_name='xodim'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehoueeeper', to=settings.AUTH_USER_MODEL, verbose_name='xodim'),
        ),
    ]
