# Generated by Django 4.2.5 on 2023-11-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0005_alter_sales_user_alter_warehouse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('sum', "So'm"), ('$', 'USD')], default='$', max_length=3, verbose_name='Valyuta birligi'),
        ),
        migrations.AddField(
            model_name='sales',
            name='buyer',
            field=models.CharField(default=1, max_length=100, verbose_name='Xaridor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.FloatField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='quantity',
            field=models.FloatField(verbose_name='Miqdor'),
        ),
    ]
