# Generated by Django 4.2.5 on 2023-11-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0007_warehouse_quantity_in_measurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Miqdor')),
                ('quantity_in_measurement', models.FloatField(verbose_name='Miqdor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anvaraka_sklad.product', verbose_name='product')),
            ],
        ),
    ]
