# Generated by Django 4.2.5 on 2023-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0010_alter_productcomponent_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity_in_measurement',
            field=models.FloatField(unique=True, verbose_name='Miqdor'),
        ),
    ]
