# Generated by Django 4.2.5 on 2023-11-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0011_alter_productcomponent_quantity_in_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='Anvaraka_sklad.product', verbose_name='product'),
        ),
    ]
