# Generated by Django 4.2.5 on 2023-11-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0012_alter_productcomponent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantity_in_measurement',
            field=models.FloatField(default=0, verbose_name='Miqdor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Dona'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(verbose_name='Dona'),
        ),
    ]
