# Generated by Django 4.2.5 on 2023-11-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anvaraka_sklad', '0014_alter_productcomponent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name="To'lov")),
                ('paid', models.DateTimeField(auto_now_add=True, verbose_name="T'olov qilingan sana")),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Anvaraka_sklad.sales')),
            ],
            options={
                'verbose_name': "To'lov ",
                'verbose_name_plural': "To'lovlar",
            },
        ),
    ]
