# Generated by Django 4.2.5 on 2023-10-12 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price', models.FloatField(verbose_name='Narx')),
                ('measurement', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('pc', 'Dona')], max_length=2, verbose_name="O'lchov birligi")),
                ('total', models.FloatField(default=0, verbose_name='Umumiy')),
                ('notification_limit', models.IntegerField(default=500, verbose_name='Ogohlantirish')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='seh_1.component', verbose_name="Bo'limlar")),
            ],
            options={
                'verbose_name': 'Komponent ',
                'verbose_name_plural': 'Komponentlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price', models.FloatField(verbose_name='Sotuv narxi')),
                ('total_new', models.IntegerField(default=0, verbose_name='Kesilmaganlar soni')),
                ('total_cut', models.IntegerField(default=0, verbose_name='Kesilganlar soni')),
                ('total_sold', models.IntegerField(default=0, verbose_name='sotilganlar soni')),
                ('total_sold_price', models.FloatField(default=0, verbose_name='Umumiy sotilgan narxi')),
            ],
            options={
                'verbose_name': 'Produkt ',
                'verbose_name_plural': 'Produktlar',
            },
        ),
        migrations.CreateModel(
            name='ProductProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=50, verbose_name='Seriya')),
                ('quantity', models.PositiveIntegerField(verbose_name='Kesilmaganlar soni')),
                ('total_cut', models.IntegerField(default=0, verbose_name='Kesilganlar soni')),
                ('total_sold', models.IntegerField(default=0, verbose_name='sotilganlar soni')),
                ('production_date', models.DateTimeField(auto_now_add=True, verbose_name='Ishlab chiqarilish vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product', verbose_name='Produkt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='xodim')),
            ],
            options={
                'verbose_name': 'Tovar ',
                'verbose_name_plural': 'Ishlab Chiqarilgan Tovarlar',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=250, verbose_name='Haridor')),
                ('seller', models.CharField(max_length=250, verbose_name='Sotuvchi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan sana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Sotuv ',
                'verbose_name_plural': "Sotuv Bo'limi ",
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('price', models.FloatField(default=0, verbose_name='Narxi')),
                ('arrival_time', models.DateTimeField(auto_now_add=True, verbose_name='Keltirilgan sana')),
                ('component', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.component', verbose_name='Komponent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='xodim')),
            ],
            options={
                'verbose_name': 'Keltirilgan Komponentlar ',
                'verbose_name_plural': 'Ombor',
            },
        ),
        migrations.CreateModel(
            name='ProductReProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_production_date', models.DateTimeField(auto_now_add=True, verbose_name='Kesilgan vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Kesilgan tovarlar ',
                'verbose_name_plural': "Kesish Bo'limi",
            },
        ),
        migrations.CreateModel(
            name='CuttingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_cut', models.PositiveIntegerField(verbose_name='Kesilganlar soni')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Sotilganlar soni')),
                ('product_production', models.ForeignKey(limit_choices_to={'total_cut': 0, 'total_sold': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction', verbose_name='Tovar')),
                ('product_reproduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting', to='seh_1.productreproduction')),
            ],
            options={
                'verbose_name': 'Kesish',
                'verbose_name_plural': 'Kesish',
                'unique_together': {('product_production', 'product_reproduction')},
            },
        ),
        migrations.CreateModel(
            name='SalesEvent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(verbose_name='Sotilganlar soni')),
                ('single_sold_price', models.FloatField(verbose_name='sotilgan narxi')),
                ('total_sold_price', models.FloatField(verbose_name='Umumiy sotilgan narxi')),
                ('non_cut_product', models.ForeignKey(limit_choices_to={'quantity__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling', to='seh_1.sales')),
            ],
            options={
                'verbose_name': 'Kesilmagan mahsulot',
                'verbose_name_plural': 'Kesilmagan mahsulot',
                'unique_together': {('non_cut_product', 'sales')},
            },
        ),
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(verbose_name='Sotilganlar soni')),
                ('single_sold_price', models.FloatField(verbose_name='sotilgan narxi')),
                ('total_sold_price', models.FloatField(verbose_name='Umumiy sotilgan narxi')),
                ('cut_product', models.ForeignKey(limit_choices_to={'quantity_cut__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.cuttingevent')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_cut', to='seh_1.sales')),
            ],
            options={
                'verbose_name': 'Kesilgan mahsulot',
                'verbose_name_plural': 'Kesilgan mahsulotlar',
                'unique_together': {('cut_product', 'sales')},
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='miqdor')),
                ('component', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.component', verbose_name='Komponent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product', verbose_name='product')),
            ],
            options={
                'unique_together': {('product', 'component')},
            },
        ),
    ]
