# Generated by Django 4.2.5 on 2023-09-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('measurement', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('pc', 'Dona')], max_length=2, verbose_name="O'lchov birligi")),
                ('total', models.FloatField(default=0, verbose_name='umumiy')),
            ],
            options={
                'verbose_name': 'Komponent ',
                'verbose_name_plural': 'Komponentlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Produkt ',
                'verbose_name_plural': 'Produktlar',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('arrival_time', models.DateTimeField(auto_now_add=True, verbose_name='Keltirilgan sana')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.component', verbose_name='Komponent')),
            ],
            options={
                'verbose_name': 'Keltirilgan Komponentlar ',
                'verbose_name_plural': 'Ombor',
            },
        ),
        migrations.CreateModel(
            name='ProductProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=50, verbose_name='Seriya')),
                ('quantity', models.PositiveIntegerField()),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('kesilgan', 'Kesilgan'), ('kesilmagan', 'Kesilmagan')], default='kesilmagan', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product', verbose_name='Produkt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='xodim')),
            ],
            options={
                'verbose_name': 'Tovar ',
                'verbose_name_plural': 'Ishlab Chiqarilgan Tovarlar',
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='miqdor')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.component', verbose_name='Komponent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product', verbose_name='product')),
            ],
            options={
                'unique_together': {('product', 'component')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(through='seh_1.ProductComponent', to='seh_1.component', verbose_name='Komponentlar'),
        ),
    ]
