# Generated by Django 4.2.5 on 2023-09-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(through='seh_1.ProductComponent', to='seh_1.component'),
        ),
    ]
