# Generated by Django 4.2.5 on 2023-10-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesevent',
            name='single_sold_price',
            field=models.FloatField(default=0, verbose_name='sotilgan narxi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent2',
            name='single_sold_price',
            field=models.FloatField(default=0.0, verbose_name='sotilgan narxi'),
            preserve_default=False,
        ),
    ]
