# Generated by Django 4.2.5 on 2023-09-10 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seh_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='xodim'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='production_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ishlab chiqarilish vaqti'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='xodim'),
        ),
    ]
