# Generated by Django 4.2.5 on 2023-11-09 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingevent',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name="Seriyadagi mahsulot kesib bo'lindi"),
        ),
        migrations.AlterField(
            model_name='cuttingevent',
            name='product_production',
            field=models.ForeignKey(limit_choices_to={'cutting_complate': False, 'quantity__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction', verbose_name='Tovar'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='cutting_complate',
            field=models.BooleanField(default=False, verbose_name='ishlab chiqarilgan maxsulotni kesish yakunlandi'),
        ),
        migrations.AlterField(
            model_name='salesevent',
            name='cut_product',
            field=models.ForeignKey(limit_choices_to={'total_cut__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction'),
        ),
        migrations.AlterField(
            model_name='salesevent2',
            name='non_cut_product',
            field=models.ForeignKey(limit_choices_to={'quantity__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction'),
        ),
    ]
