# Generated by Django 4.2.5 on 2023-09-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0002_alter_warehouse_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(limit_choices_to={'parent__isnull': False}, through='seh_1.ProductComponent', to='seh_1.component', verbose_name='Komponentlar'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.component', verbose_name='Komponent'),
        ),
    ]
