# Generated by Django 4.2.5 on 2023-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0002_salesevent_single_sold_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='price',
            field=models.FloatField(default=0, verbose_name='Narxi'),
        ),
    ]
