# Generated by Django 4.2.5 on 2023-09-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0002_warehouse_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='seh_1.component', verbose_name="Bo'lim"),
        ),
    ]
