# Generated by Django 4.2.5 on 2023-11-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0002_alter_cuttingevent_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproduction',
            options={'ordering': ['-production_date'], 'verbose_name': 'Tovar ', 'verbose_name_plural': 'Ishlab Chiqarilgan Tovarlar'},
        ),
    ]
