# Generated by Django 4.2.5 on 2023-11-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0002_cuttingevent_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproduction',
            name='cutting_complate',
            field=models.BooleanField(default=False),
        ),
    ]
