# Generated by Django 4.2.5 on 2023-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0002_product_productcomponent_product_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
