# Generated by Django 4.2.5 on 2023-09-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0003_alter_productcomponent_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomponent',
            unique_together={('product', 'component')},
        ),
    ]
