# Generated by Django 4.2.5 on 2023-10-07 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0003_warehouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingevent',
            name='product_production',
            field=models.ForeignKey(limit_choices_to={'total_cut': 0, 'total_sold': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction', verbose_name='Tovar'),
        ),
        migrations.AlterField(
            model_name='productreproduction',
            name='re_production_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kesilgan vaqti'),
        ),
    ]
