# Generated by Django 4.2.5 on 2023-09-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0003_alter_product_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='notification_limit',
            field=models.IntegerField(default=500, verbose_name='Ogohlantirish'),
        ),
    ]
