# Generated by Django 4.2.5 on 2023-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0004_component_notification_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproduction',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='total_cut',
            field=models.IntegerField(default=0, verbose_name='Kesilmaganlar soni'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_new',
            field=models.IntegerField(default=0, verbose_name='Kesilmaganlar soni'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0, verbose_name='Kesilmaganlar soni'),
        ),
    ]
