# Generated by Django 4.2.5 on 2023-09-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0004_alter_productcomponent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('series', models.IntegerField()),
                ('production_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product')),
            ],
        ),
    ]
