# Generated by Django 4.2.5 on 2023-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0005_productproduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': '1. Component', 'verbose_name_plural': '1. Components'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '2. Products'},
        ),
        migrations.AlterModelOptions(
            name='productproduction',
            options={'verbose_name': '3. Production', 'verbose_name_plural': '3. Productions'},
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='production_date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
