# Generated by Django 4.2.5 on 2023-11-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0005_productproduction_level_productproduction_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproduction',
            options={'ordering': ['-production_date'], 'verbose_name': 'Tovar ', 'verbose_name_plural': 'Ishlab Chiqarilgan Tovarlar'},
        ),
        migrations.AlterField(
            model_name='cuttingevent',
            name='product_production',
            field=models.ForeignKey(limit_choices_to={'cutting_complate': False, 'parent__isnull': True, 'quantity__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction', verbose_name='Tovar'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='seh_1.productproduction', verbose_name="Bo'limlar"),
        ),
    ]
