# Generated by Django 4.2.5 on 2023-09-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0005_remove_productproduction_status_product_total_cut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduction',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdori'),
        ),
    ]
