# Generated by Django 4.2.5 on 2023-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0006_alter_productreproduction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='price',
            field=models.FloatField(default=1, verbose_name='Narx'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='total',
            field=models.FloatField(default=0, verbose_name='Umumiy'),
        ),
    ]
