# Generated by Django 4.2.5 on 2023-11-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0006_alter_productproduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduction',
            name='cutting_complate',
            field=models.BooleanField(default=False, verbose_name='kesish yakunlandi'),
        ),
        migrations.AlterField(
            model_name='salesevent',
            name='cut_product',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True, 'total_cut__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction'),
        ),
        migrations.AlterField(
            model_name='salesevent2',
            name='non_cut_product',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True, 'quantity__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction'),
        ),
    ]
