# Generated by Django 4.2.5 on 2023-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0006_alter_component_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduction',
            name='production_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
