# Generated by Django 4.2.5 on 2023-11-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0007_alter_productproduction_cutting_complate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduction',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'cutting_complate': False, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='seh_1.productproduction', verbose_name="Bo'limlar"),
        ),
    ]
