# Generated by Django 4.2.5 on 2023-09-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0007_alter_productproduction_production_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Komponent ', 'verbose_name_plural': '1. Komponentlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt ', 'verbose_name_plural': '2. Produktlar'},
        ),
        migrations.AlterModelOptions(
            name='productproduction',
            options={'verbose_name': '3. Tovar ', 'verbose_name_plural': '3. Ishlab Chiqarilgan Tovarlar'},
        ),
        migrations.AlterField(
            model_name='component',
            name='measurement',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece')], max_length=2, verbose_name="O'lchov birligi"),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(through='seh_1.ProductComponent', to='seh_1.component', verbose_name='Komponentlar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='series',
            field=models.IntegerField(verbose_name='Seriya'),
        ),
    ]
