# Generated by Django 4.2.5 on 2023-09-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0007_alter_product_total_cut_alter_product_total_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproduction',
            name='total_cut',
            field=models.IntegerField(default=0, verbose_name='Kesilganlar soni'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='total_sold',
            field=models.IntegerField(default=0, verbose_name='sotilganlar soni'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Kesilmaganlar soni'),
        ),
    ]
