# Generated by Django 4.2.5 on 2023-10-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0007_component_price_alter_component_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=4.5, verbose_name='Sotuv narxi'),
            preserve_default=False,
        ),
    ]
