# Generated by Django 4.2.5 on 2023-09-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0008_alter_component_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='measurement',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('pc', 'Dona')], max_length=2, verbose_name="O'lchov birligi"),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.component', verbose_name='Komponent'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity',
            field=models.FloatField(verbose_name='miqdor'),
        ),
    ]
