# Generated by Django 4.2.5 on 2023-09-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seh_1', '0008_productproduction_total_cut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.cutproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='xodim')),
            ],
            options={
                'verbose_name': 'Produkt reproduksiya',
                'verbose_name_plural': 'Produkt reproduksiyalari',
            },
        ),
    ]
