# Generated by Django 4.2.5 on 2023-12-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0008_alter_productproduction_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproduction',
            options={'ordering': ['-id'], 'verbose_name': 'Tovar ', 'verbose_name_plural': 'Ishlab Chiqarilgan Tovarlar'},
        ),
        migrations.RenameField(
            model_name='productproduction',
            old_name='production_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='productreproduction',
            old_name='re_production_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='cuttingevent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='salesevent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='salesevent2',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='cutting_complate',
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='level',
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='total_cut',
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='total_sold',
        ),
        migrations.RemoveField(
            model_name='productproduction',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='cuttingevent',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'total_new__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.product', verbose_name='Tovar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreproduction',
            name='series',
            field=models.CharField(default=1, max_length=50, verbose_name='Seriya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='series',
            field=models.CharField(default=1, max_length=50, verbose_name='Seriya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'total_cut__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent2',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'total_new__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cuttingevent',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='cuttingevent',
            name='product_production',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='cut_product',
        ),
        migrations.RemoveField(
            model_name='salesevent2',
            name='non_cut_product',
        ),
    ]
