# Generated by Django 4.2.5 on 2023-09-12 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0009_cutproduct_productreproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreproduction',
            name='reproduction_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
