# Generated by Django 4.2.5 on 2023-12-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0009_alter_productproduction_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesevent',
            unique_together={('product', 'sales')},
        ),
        migrations.AlterUniqueTogether(
            name='salesevent2',
            unique_together={('product', 'sales')},
        ),
    ]
