# Generated by Django 4.2.5 on 2023-09-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0009_alter_component_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduction',
            name='series',
            field=models.CharField(max_length=50, verbose_name='Seriya'),
        ),
    ]
