# Generated by Django 4.2.5 on 2023-12-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0010_alter_salesevent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuttingevent',
            unique_together={('product', 'product_reproduction')},
        ),
    ]
