# Generated by Django 4.2.5 on 2023-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0010_productreproduction_reproduction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreproduction',
            name='cutproduct',
        ),
        migrations.AddField(
            model_name='productreproduction',
            name='cutproduct',
            field=models.ManyToManyField(to='seh_1.cutproduct'),
        ),
    ]
