# Generated by Django 4.2.5 on 2023-09-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0011_productproduction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproduction',
            options={'verbose_name': 'Tovar ', 'verbose_name_plural': '3. Ishlab Chiqarilgan Tovarlar'},
        ),
    ]
