# Generated by Django 4.2.5 on 2023-09-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0011_remove_productreproduction_cutproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreproduction',
            name='cutproduct',
        ),
        migrations.RemoveField(
            model_name='productreproduction',
            name='user',
        ),
        migrations.DeleteModel(
            name='CutProduct',
        ),
        migrations.DeleteModel(
            name='ProductReProduction',
        ),
    ]
