# Generated by Django 4.2.5 on 2024-01-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0011_alter_cuttingevent_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_sold_price',
        ),
    ]
