# Generated by Django 4.2.5 on 2024-01-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0012_remove_product_total_sold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesevent',
            name='profit',
            field=models.FloatField(default=0, verbose_name='Foyde'),
        ),
    ]
