# Generated by Django 4.2.5 on 2023-09-12 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seh_1', '0012_remove_productreproduction_cutproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_production_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuttingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_cut', models.PositiveIntegerField(verbose_name='Kesilganlar soni')),
                ('product_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction')),
            ],
            options={
                'verbose_name': 'Cutting Event',
                'verbose_name_plural': 'Cutting Events',
            },
        ),
    ]
