# Generated by Django 4.2.5 on 2023-09-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seh_1', '0012_alter_productproduction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Komponent ', 'verbose_name_plural': 'Komponentlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt ', 'verbose_name_plural': 'Produktlar'},
        ),
        migrations.AlterModelOptions(
            name='productproduction',
            options={'verbose_name': 'Tovar ', 'verbose_name_plural': 'Ishlab Chiqarilgan Tovarlar'},
        ),
        migrations.AddField(
            model_name='productproduction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='xodim'),
        ),
    ]
