# Generated by Django 4.2.5 on 2024-01-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0013_salesevent_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesevent2',
            name='profit',
            field=models.FloatField(default=0, verbose_name='Foyda'),
        ),
        migrations.AlterField(
            model_name='salesevent',
            name='profit',
            field=models.FloatField(default=0, verbose_name='Foyda'),
        ),
    ]
