# Generated by Django 4.2.5 on 2023-09-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0014_cuttingevent_product_reproduction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuttingevent',
            unique_together={('product_production', 'product_reproduction')},
        ),
    ]
