# Generated by Django 4.2.5 on 2023-09-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0016_alter_cuttingevent_product_reproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingevent',
            name='product_production',
            field=models.ForeignKey(limit_choices_to=models.Q(('total_cut__gt', 0)), on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction'),
        ),
    ]
