# Generated by Django 4.2.5 on 2024-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0016_alter_salesevent_options_alter_salesevent2_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invalid_price',
            field=models.FloatField(default=3, verbose_name='Yaroqsiz tovar narxi'),
            preserve_default=False,
        ),
    ]
