# Generated by Django 4.2.5 on 2023-09-17 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seh_1', '0018_alter_cuttingevent_product_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=250, verbose_name='Haridor')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productreproduction',
            options={'verbose_name': 'Kesilgan tovarlar ', 'verbose_name_plural': "Kesish Bo'limi"},
        ),
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(verbose_name='Sotilganlar soni')),
                ('cut_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling', to='seh_1.sales')),
            ],
        ),
    ]
