# Generated by Django 4.2.5 on 2023-09-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0019_sales_alter_productreproduction_options_salesevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesevent',
            name='cut_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.cuttingevent'),
        ),
    ]
