# Generated by Django 4.2.5 on 2023-09-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0020_alter_salesevent_cut_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesevent',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_cut', to='seh_1.sales'),
        ),
        migrations.CreateModel(
            name='SalesEvent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(verbose_name='Sotilganlar soni')),
                ('non_cut_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling', to='seh_1.sales')),
            ],
        ),
    ]
