# Generated by Django 4.2.5 on 2023-09-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0021_alter_salesevent_sales_salesevent2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesevent',
            name='cut_product',
            field=models.ForeignKey(limit_choices_to={'quantity_cut': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.cuttingevent'),
        ),
        migrations.AlterField(
            model_name='salesevent2',
            name='non_cut_product',
            field=models.ForeignKey(limit_choices_to={'quantity': 0}, on_delete=django.db.models.deletion.CASCADE, to='seh_1.productproduction'),
        ),
    ]
