# Generated by Django 4.2.5 on 2023-09-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0023_alter_salesevent_cut_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesevent',
            options={'verbose_name': 'Sales Event', 'verbose_name_plural': 'Sales Events'},
        ),
        migrations.AlterModelOptions(
            name='salesevent2',
            options={'verbose_name': 'Sales Event2', 'verbose_name_plural': 'Sales Event2s'},
        ),
        migrations.AlterUniqueTogether(
            name='salesevent',
            unique_together={('cut_product', 'sales')},
        ),
        migrations.AlterUniqueTogether(
            name='salesevent2',
            unique_together={('non_cut_product', 'sales')},
        ),
    ]
