# Generated by Django 4.2.5 on 2023-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0024_alter_salesevent_options_alter_salesevent2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingevent',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Sotilganlar soni'),
        ),
    ]
