# Generated by Django 4.2.5 on 2023-09-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0025_cuttingevent_quantity_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuttingevent',
            options={'verbose_name': 'Kesish', 'verbose_name_plural': 'Kesish'},
        ),
        migrations.AlterModelOptions(
            name='salesevent',
            options={'verbose_name': 'Kesilgan mahsulot', 'verbose_name_plural': 'Kesilgan mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='salesevent2',
            options={'verbose_name': 'Kesilmagan mahsulot', 'verbose_name_plural': 'Kesilmagan mahsulot'},
        ),
    ]
