# Generated by Django 4.2.5 on 2023-09-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0026_alter_cuttingevent_options_alter_salesevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sotuv ', 'verbose_name_plural': "Sotuv Bo'limi "},
        ),
    ]
