# Generated by Django 4.2.5 on 2023-09-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seh_1', '0027_alter_sales_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
    ]
