"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from environs import Env

env = Env()
env.read_env()

TOKEN = env.str('TOKEN')
ADMINS = env.list('ADMINS')
HOSTNAME = env.str('HOSTNAME')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kh^ce^2&9sw%_0of$9zd5i766(%&k53*8@(#k1w2fj2xs39g_2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mptt',
    'seh_1',
    'Anvaraka_sklad',
    'Azamat_seh',
]

LOGIN_URL = '/admin/login/'
CSRF_TRUSTED_ORIGINS = [
    'https://abdurahmonovjamshid.jprq.live',
    'https://saxiyhamkor.pythonanywhere.com/'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'seh_1.middleware.ComponentNotificationMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'
SESSION_COOKIE_AGE = 60 * 30
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


JAZZMIN_SETTINGS = {
    "site_title": "Sahiy Hamkor",
    "site_header": "Library",
    "site_brand": "Saxiy Hamkor",
    "site_logo": "logo/logo.png",
    "search_model": ["auth.User"],
    # "show_ui_builder": True,

    "usermenu_links": [
        {"name": "Support", "url": "https://t.me/Jamshid_Abdurahmonov1",
            "new_window": True},
        {"model": "auth.user"}
    ],

    "topmenu_links": [

        {"name": "Home",  "url": "admin:index",
            "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://t.me/Jamshid_Abdurahmonov1",
            "new_window": True},
        {"model": "auth.User"},
        {"app": "seh_1"},
        {"app": "Azamat_seh"},
        {"app": "Anvaraka_sklad"},

    ],
    "show_sidebar": True,
    "order_with_respect_to": ["auth", "seh_1", "Azamat_Seh", "seh_1.component", "seh_1.product", "seh_1.warehouse", "seh_1.productproduction", 'seh_1.productreproduction',
                              'Azamat_Seh.component', 'Azamat_Seh.product', 'Azamat_Seh.warehouse', 'Azamat_Seh.productproduction', 'Azamat_Seh.sales',
                              "Anvaraka_sklad.product", "Anvaraka_sklad.warehouse", "Anvaraka_sklad.selling",],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "seh_1.component": "fas fa-cubes",
        "seh_1.product": "fas fa-shopping-bag",
        "seh_1.productproduction": "fas fa-industry",
        "seh_1.warehouse": "fas fa-warehouse",
        "seh_1.productreproduction": "fas fa-cut",
        "seh_1.sales": "fas fa-shopping-cart",

        "Azamat_Seh.component": "fas fa-cubes",
        "Azamat_Seh.product": "fas fa-shopping-bag",
        "Azamat_Seh.productproduction": "fas fa-industry",
        "Azamat_Seh.warehouse": "fas fa-warehouse",
        "Azamat_Seh.sales": "fas fa-shopping-cart",

        "Anvaraka_sklad.product": "fas fa-cubes",
        "Anvaraka_sklad.warehouse": "fas fa-warehouse",
        "Anvaraka_sklad.selling": "fas fa-shopping-cart",
    },
}

# JAZZMIN_UI_TWEAKS = {
#     "theme": "default",
#     "dark_mode_theme": "darkly",
# }

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz-uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = 'static'
STATIC_ROOT = 'static'
STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'staticfiles'),
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
